# Identifiant unique de ton projet (doit correspondre à celui créé dans SonarQube)
sonar.projectKey=plateforme-examen
sonar.projectName=Plateforme Examen

# Emplacement du code source
sonar.sources=.

# Exclusions (Très important pour ne pas analyser les bibliothèques tierces)
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/venv/**, **/*.spec.ts, **/tests/**

# Configuration pour le Backend (Python)
sonar.python.version=3
sonar.python.xunit.reportPath=backend/test-reports/results.xml

# Configuration pour le Frontend (JS/TS)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.sourceEncoding=UTF-8