sonar.projectKey=plateforme-examen
sonar.projectName=plateforme-examen
sonar.sourceEncoding=UTF-8
sonar.sources=backend,frontend/src
sonar.exclusions=backend/venv/**,frontend/node_modules/**,frontend/dist/**,**/__pycache__/**,**/*.min.js
