apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: plateforme-examen
  labels:
    app.kubernetes.io/name: plateforme-examen
    app.kubernetes.io/component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: FRONTEND_IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
          # Pas de env ici — Vite a déjà buildé avec la bonne URL
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: plateforme-examen
spec:
  selector:
    app: frontend
  ports:
    - port: 4173
      targetPort: 4173
  type: ClusterIP   # ← Interne uniquement, NGINX fait le routag
  