apiVersion: v1
kind: Secret
metadata:
  name: plateforme-examen-secrets
  namespace: plateforme-examen
  labels:
    app.kubernetes.io/name: plateforme-examen
type: Opaque
# Remplacez les valeurs CHANGEME_* avant d'appliquer
# En prod : utilisez Sealed Secrets ou External Secrets Operator
stringData:
  POSTGRES_DB: "exam_db"
  POSTGRES_USER: "exam_user"
  POSTGRES_PASSWORD: "CHANGEME_postgres_password"
  SECRET_KEY: "CHANGEME_secret_key"
  JWT_SECRET_KEY: "CHANGEME_jwt_secret_key"