"""add_is_archived_and_retake_requests

Revision ID: b16c1735ab50
Revises: 7bd28216f527
Create Date: 2026-04-25 04:48:23.482279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16c1735ab50'
down_revision = '7bd28216f527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retake_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', 'status', name='uq_retake_pending')
    )
    with op.batch_alter_table('retake_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retake_requests_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retake_requests_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retake_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_retake_requests_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('is_archived')

    with op.batch_alter_table('retake_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retake_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_retake_requests_status'))
        batch_op.drop_index(batch_op.f('ix_retake_requests_exam_id'))
        batch_op.drop_index(batch_op.f('ix_retake_requests_attempt_id'))

    op.drop_table('retake_requests')
    # ### end Alembic commands ###
